spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security # Database connection URL
    username: root # Database username
    password: Bhanu@898 # Database password
    driverClassName: com.mysql.cj.jdbc.Driver # JDBC Driver class name
    platform: mysql # Database platform
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect # Hibernate dialect for MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect # Hibernate platform for MySQL
    hibernate:
      ddl-auto: update # Automatically update database schema
    show-sql: true # Log SQL queries

